/** Declaration file generated by dts-gen */

declare module "botometer" {
    export class Botometer {
        constructor(_options: any)

        checkAccount(twitterData: any): any

        errorLog(message: any, ...args: any[]): void

        getScore(name: any): any

        getScoreFor(name: any): any

        getScores(names: any): any

        getScoresGenerator(names: any, ...args: any[]): any

        getTwitterData(name: any): any

        log(message: any, ...args: any[]): void

        parseBotometerApiError(e: any): any

        parseTwitterApiError(e: any): any
    }
}
